language: python
sudo: required
dist: trusty

branches:
  except:
    - gh-pages

osx_image: xcode8.2
dist: trusty
sudo: required

matrix:
  exclude:
    - os: linux
    - os: osx

  include:
  - os: linux
    python: 3.6
  - os: osx
    python: 3.6

install: 
  - source scripts/split_repo_slug.sh
  - scripts/install-deps.sh
  - travis_wait scripts/install.sh

script: echo "Less is More"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ${SECURE_KEY}
  file:
  - "src/dist/${REPO}_${TRAVIS_TAG}_${TRAVIS_OS_NAME}.zip"
  on:
    tags: true
    all_branches: true
    repo: ${TRAVIS_REPO_SLUG}
